### ISSUE TITLE
Deploy no vercel não busca da minha planilha

### ISSUE THREAD

**Issue by ronaldmaymone** [zehfernandes/brazilianswhodesign#10]
Ao rodar localmente ele usa a planilha como deveria, mas após o Deploy o site busca os dados de alguma outra planilha que está como default.
Poderia me dar uma luz no que errei?
A princípio configurei tudo como deveria. Segue o designers.js com o ID alterado:

```javascript
import drive from "drive-db";

export default async (req, res) => {
  const db = await drive("1RLGOdHcOx1SoayyziY0Z50sWrHRSnGudKzSdkjq7i94");
  let sanitizeResult = db.filter(
    (item) => item.name != "" && item.show == "Yes"
  );

  res.statusCode = 200;
  res.setHeader("Content-Type", "application/json");
  res.end(JSON.stringify(sanitizeResult));
};
 ```

Existe alguma outra configuração necessária na planilha além de publicar na web?

**Comment by zehfernandes** [comment]
Olá Ronald.

Você precisa alterar esta linha para a URL do seu site em produção: 
https://github.com/zehfernandes/brazilianswhodesign/blob/eb8083efb2776f8008f5c4b35409d436f71ee17c/pages/index.js#L15

**Comment by ronaldmaymone** [comment]
Foi aqui, muito obrigado pela resposta rápida :)
