### ISSUE TITLE
drive-db no longer works

### ISSUE THREAD

**Issue by tellaho** [zehfernandes/brazilianswhodesign#13]
Just wanted to pass some information along since we forked this project and ran into the build failing a week or so ago.

Some troubleshooting led us to find that the `drive-db` package [appears to be broken](https://github.com/franciscop/drive-db/issues/14) after a change to Google's Sheets API. 🤷‍♂️

**Comment by zehfernandes** [comment]
Fixed. You need to create google credentials and add them to your .env file.
