### ISSUE TITLE
Link errado na página About

### ISSUE THREAD

**Issue by juliostc** [zehfernandes/brazilianswhodesign#2]
Olá, tudo bem?
Parabéns pelo trabalho no site!
Passando para avisar que na página [about](https://brazilianswho.design/about)  o link para o site People of Craft está errado, redirecionando para o Filipinos Who Design (o mesmo que vem logo antes)

Abraços!

**Comment by zehfernandes** [comment]
Obrigado @juliostc !

Link atualizado. 🙌
